version: '3.8'
services:
  crashCourseDb: 
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER: myuser
      - POSTGRES_PASSWORD: strongpassword
      - POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
